In [5]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Dec 28 04:14:32 2019

@author: Ajinkya B
"""

'\nCreated on Dec 28 04:14:32 2019\n\n@author: Ajinkya B\n'

In [6]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as mpl

In [7]:
help("modules")


Please wait a moment while I gather a list of all available modules...



/opt/anaconda3/lib/python3.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/opt/anaconda3/lib/python3.7/site-packages/nltk/twitter/__init__.py:22: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  "The twython library has not been installed. "


DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: bzr
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: git
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: hg
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: svn


/opt/anaconda3/lib/python3.7/site-packages/skimage/novice/__init__.py:103: UserWarning: The `skimage.novice` module was deprecated in version 0.14. It will be removed in 0.16.
  warnings.warn("The `skimage.novice` module was deprecated in version 0.14. "
/opt/anaconda3/lib/python3.7/site-packages/skimage/viewer/utils/core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "
/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/opt/anaconda3/lib/python3.7/site-packages/qtawesome/iconic_fo

Crypto              brain_hashlib       itsdangerous        re
Cython              brain_http          jdcal               readline
IPython             brain_io            jedi                reprlib
OpenSSL             brain_mechanize     jinja2              requests
PIL                 brain_multiprocessing joblib              resource
PyQt5               brain_namedtuple_enum json                rlcompleter
__future__          brain_nose          json5               rmagic
_abc                brain_numpy_core_fromnumeric jsonschema          rope
_ast                brain_numpy_core_function_base jupyter             ruamel_yaml
_asyncio            brain_numpy_core_multiarray jupyter_client      runpy
_bisect             brain_numpy_core_numeric jupyter_console     sched
_blake2             brain_numpy_core_numerictypes jupyter_core        scipy
_bootlocale         brain_numpy_core_umath jupyterlab          scripts
_bz2                brain_numpy_ndarray jupyterlab_server   seaborn
_c

/opt/anaconda3/lib/python3.7/pkgutil.py:107: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)


In [8]:
#importing datasets
dataset = pd.read_csv("NormalizedData.csv")
x = dataset.iloc[:,:-1].values
a = pd.DataFrame(x)
y = dataset.iloc[:,9].values
b = pd.DataFrame(y)

In [10]:
len(dataset)

400

In [11]:
list(dataset.columns)

['student_id',
 'grescore',
 'toeflscore',
 'universityrating',
 'sop',
 'lor',
 'cgpa',
 'research',
 'location',
 'chanceofadmit']

In [12]:
list(a.columns)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
a.columns = ['student_id',
 'grescore',
 'toeflscore',
 'universityrating',
 'sop',
 'lor',
 'cgpa',
 'research',
 'location']

In [14]:
a

student_id grescore toeflscore universityrating  sop  lor  cgpa research  \
0            1      337        118                4  4.5  4.5  9.65        1   
1            2      324        107                4    4  4.5  8.87        1   
2            3      316        104                3    3  3.5     8        1   
3            4      322        110                3  3.5  2.5  8.67        1   
4            5      314        103                2    2    3  8.21        0   
..         ...      ...        ...              ...  ...  ...   ...      ...   
395        396      324        110                3  3.5  3.5  9.04        1   
396        397      325        107                3    3  3.5  9.11        1   
397        398      330        116                4    5  4.5  9.45        1   
398        399      312        103                3  3.5    4  8.78        0   
399        400      333        117                4    5    4  9.66        1   

    location  
0      India  
1        USA  
2        USA  
3        USA  
4         UK  
..       ...  
395      USA  
396      USA  
397      USA  
398      USA  
399      USA  

[400 rows x 9 columns]

In [15]:
b

0
0    0.92
1    0.76
2    0.72
3    0.80
4    0.65
..    ...
395  0.82
396  0.84
397  0.91
398  0.67
399  0.95

[400 rows x 1 columns]

In [17]:
b.columns=["Admit Chances"]

In [18]:
b

Admit Chances
0             0.92
1             0.76
2             0.72
3             0.80
4             0.65
..             ...
395           0.82
396           0.84
397           0.91
398           0.67
399           0.95

[400 rows x 1 columns]

In [19]:
import seaborn as sns

In [20]:
#Encoding Categorial Data
#Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Encoder_a = LabelEncoder()
a["location"] = Encoder_a.fit_transform(a["location"])

In [22]:
a

student_id grescore toeflscore universityrating  sop  lor  cgpa research  \
0            1      337        118                4  4.5  4.5  9.65        1   
1            2      324        107                4    4  4.5  8.87        1   
2            3      316        104                3    3  3.5     8        1   
3            4      322        110                3  3.5  2.5  8.67        1   
4            5      314        103                2    2    3  8.21        0   
..         ...      ...        ...              ...  ...  ...   ...      ...   
395        396      324        110                3  3.5  3.5  9.04        1   
396        397      325        107                3    3  3.5  9.11        1   
397        398      330        116                4    5  4.5  9.45        1   
398        399      312        103                3  3.5    4  8.78        0   
399        400      333        117                4    5    4  9.66        1   

     location  
0           1  
1           7  
2           7  
3           7  
4           6  
..        ...  
395         7  
396         7  
397         7  
398         7  
399         7  

[400 rows x 9 columns]

In [23]:
a.shape

(400, 9)

In [24]:
#Encoding Categorial Data
#Encoding the Independent Variable
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [8])], remainder = 'passthrough')
a = ct.fit_transform(a)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [25]:
a

array([[0.0, 1.0, 0.0, ..., 4.5, 9.65, 1],
       [0.0, 0.0, 0.0, ..., 4.5, 8.87, 1],
       [0.0, 0.0, 0.0, ..., 3.5, 8.0, 1],
       ...,
       [0.0, 0.0, 0.0, ..., 4.5, 9.45, 1],
       [0.0, 0.0, 0.0, ..., 4.0, 8.78, 0],
       [0.0, 0.0, 0.0, ..., 4.0, 9.66, 1]], dtype=object)

In [26]:
b

Admit Chances
0             0.92
1             0.76
2             0.72
3             0.80
4             0.65
..             ...
395           0.82
396           0.84
397           0.91
398           0.67
399           0.95

[400 rows x 1 columns]

In [27]:
indepv = pd.DataFrame(a)

In [28]:
indepv

0  1  2  3  4  5  6  7    8    9   10 11   12   13    14 15
0    0  1  0  0  0  0  0  0    1  337  118  4  4.5  4.5  9.65  1
1    0  0  0  0  0  0  0  1    2  324  107  4    4  4.5  8.87  1
2    0  0  0  0  0  0  0  1    3  316  104  3    3  3.5     8  1
3    0  0  0  0  0  0  0  1    4  322  110  3  3.5  2.5  8.67  1
4    0  0  0  0  0  0  1  0    5  314  103  2    2    3  8.21  0
..  .. .. .. .. .. .. .. ..  ...  ...  ... ..  ...  ...   ... ..
395  0  0  0  0  0  0  0  1  396  324  110  3  3.5  3.5  9.04  1
396  0  0  0  0  0  0  0  1  397  325  107  3    3  3.5  9.11  1
397  0  0  0  0  0  0  0  1  398  330  116  4    5  4.5  9.45  1
398  0  0  0  0  0  0  0  1  399  312  103  3  3.5    4  8.78  0
399  0  0  0  0  0  0  0  1  400  333  117  4    5    4  9.66  1

[400 rows x 16 columns]

In [29]:
#Avoiding Dummy Varibale traps
a = a[:,1:]

In [30]:
newindepv = pd.DataFrame(a)

In [31]:
newindepv

0  1  2  3  4  5  6    7    8    9 10   11   12    13 14
0    1  0  0  0  0  0  0    1  337  118  4  4.5  4.5  9.65  1
1    0  0  0  0  0  0  1    2  324  107  4    4  4.5  8.87  1
2    0  0  0  0  0  0  1    3  316  104  3    3  3.5     8  1
3    0  0  0  0  0  0  1    4  322  110  3  3.5  2.5  8.67  1
4    0  0  0  0  0  1  0    5  314  103  2    2    3  8.21  0
..  .. .. .. .. .. .. ..  ...  ...  ... ..  ...  ...   ... ..
395  0  0  0  0  0  0  1  396  324  110  3  3.5  3.5  9.04  1
396  0  0  0  0  0  0  1  397  325  107  3    3  3.5  9.11  1
397  0  0  0  0  0  0  1  398  330  116  4    5  4.5  9.45  1
398  0  0  0  0  0  0  1  399  312  103  3  3.5    4  8.78  0
399  0  0  0  0  0  0  1  400  333  117  4    5    4  9.66  1

[400 rows x 15 columns]

In [32]:
newdepv = pd.DataFrame(b)

In [33]:
newdepv

Admit Chances
0             0.92
1             0.76
2             0.72
3             0.80
4             0.65
..             ...
395           0.82
396           0.84
397           0.91
398           0.67
399           0.95

[400 rows x 1 columns]

In [34]:
newindepv.columns = ['0','1','2','3','4','5','6','student_id',
 'grescore',
 'toeflscore',
 'universityrating',
 'sop',
 'lor',
 'cgpa',
 'research']

In [35]:
newindepv

0  1  2  3  4  5  6 student_id grescore toeflscore universityrating  sop  \
0    1  0  0  0  0  0  0          1      337        118                4  4.5   
1    0  0  0  0  0  0  1          2      324        107                4    4   
2    0  0  0  0  0  0  1          3      316        104                3    3   
3    0  0  0  0  0  0  1          4      322        110                3  3.5   
4    0  0  0  0  0  1  0          5      314        103                2    2   
..  .. .. .. .. .. .. ..        ...      ...        ...              ...  ...   
395  0  0  0  0  0  0  1        396      324        110                3  3.5   
396  0  0  0  0  0  0  1        397      325        107                3    3   
397  0  0  0  0  0  0  1        398      330        116                4    5   
398  0  0  0  0  0  0  1        399      312        103                3  3.5   
399  0  0  0  0  0  0  1        400      333        117                4    5   

     lor  cgpa research  
0    4.5  9.65        1  
1    4.5  8.87        1  
2    3.5     8        1  
3    2.5  8.67        1  
4      3  8.21        0  
..   ...   ...      ...  
395  3.5  9.04        1  
396  3.5  9.11        1  
397  4.5  9.45        1  
398    4  8.78        0  
399    4  9.66        1  

[400 rows x 15 columns]

In [36]:
newindepv=newindepv.drop(columns=["0","1","2","3","4","5","6"])

In [37]:
#dropunnnecessarycolumns
newindepv=newindepv.drop(columns=["student_id"])

In [38]:
newindepv

grescore toeflscore universityrating  sop  lor  cgpa research
0        337        118                4  4.5  4.5  9.65        1
1        324        107                4    4  4.5  8.87        1
2        316        104                3    3  3.5     8        1
3        322        110                3  3.5  2.5  8.67        1
4        314        103                2    2    3  8.21        0
..       ...        ...              ...  ...  ...   ...      ...
395      324        110                3  3.5  3.5  9.04        1
396      325        107                3    3  3.5  9.11        1
397      330        116                4    5  4.5  9.45        1
398      312        103                3  3.5    4  8.78        0
399      333        117                4    5    4  9.66        1

[400 rows x 7 columns]

In [39]:
#Splitting the Dataset into Training Set and Test Set
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
a_train , a_test , b_train , b_test  = train_test_split(newindepv,newdepv,test_size = 0.2, random_state = 1)

In [102]:
b_test.shape

(80, 1)

In [41]:
b_train

Admit Chances
93            0.44
23            0.95
299           0.71
13            0.62
90            0.64
..             ...
255           0.79
72            0.93
396           0.84
235           0.88
37            0.58

[320 rows x 1 columns]

In [42]:
#Fitting multiple linear regression model to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(a_train,b_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
#Predicting the test set result
b_pred = regressor.predict(a_test)

In [103]:
b_pred.shape

(80, 1)

In [108]:
#Checking the score 
print('Train Score: ', regressor.score(a_train, b_train))  
print('Test Score: ', regressor.score(a_test, b_test))  

Train Score:  0.800877808114134
Test Score:  0.80790436770201


In [46]:
#Building Optimal Model Using Backward Elimination
#importing the statsmodels library
import statsmodels.api as sm

In [52]:
#Adding a column in matrix of features
#there is one constant term b0, but this term is not present in our matrix of features, so we need to add it manually. 
#We will add a column having values x0 = 1 associated with the constant term b0.
#To add this, we will use append function of Numpy library (nm which we have already imported into our code), and will assign a value of 1.
X = np.append(arr = np.ones(shape = (400,1)).astype(int), values = x, axis = 1)

In [69]:
#Here we have used axis =1, as we wanted to add a column. For adding a row, we can use axis =0.
X

array([[1, 1, 337, ..., 9.65, 1, 'India'],
       [1, 2, 324, ..., 8.87, 1, 'USA'],
       [1, 3, 316, ..., 8.0, 1, 'USA'],
       ...,
       [1, 398, 330, ..., 9.45, 1, 'USA'],
       [1, 399, 312, ..., 8.78, 0, 'USA'],
       [1, 400, 333, ..., 9.66, 1, 'USA']], dtype=object)

In [74]:
#since indepdv is a dataframe we convert it into a dataset again
z = newindepv.iloc[:,:].values

In [89]:
z

array([[337, 118, 4, ..., 4.5, 9.65, 1],
       [324, 107, 4, ..., 4.5, 8.87, 1],
       [316, 104, 3, ..., 3.5, 8.0, 1],
       ...,
       [330, 116, 4, ..., 4.5, 9.45, 1],
       [312, 103, 3, ..., 4.0, 8.78, 0],
       [333, 117, 4, ..., 4.0, 9.66, 1]], dtype=object)

In [82]:
w = newdepv.iloc[:,:].values

In [83]:
w

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [91]:
z.dtype

dtype('float64')

In [94]:
#apply a backward elimination process. 
#we change data type to float as well since its an object
#create a new feature vector x_opt, which will only contain a set of independent features that are significantly affecting the dependent variable.
#Next we need to choose a significant level(0.5), and then need to fit the model with all possible predictors. 
#So for fitting the model, we will create a regressor_OLS object of new class OLS of statsmodels library. 
#Then we will fit it by using the fit() method.
#p-value to compare with SL value, so we use summary() method to get the summary table.
x_opt = z[:,[0,1,2,3,4,5,6]]
x_opt = np.array(x_opt, dtype = float)
regressor_OLS = sm.OLS(endog = w, exog = x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.991
Method:                 Least Squares   F-statistic:                              6034.
Date:                Thu, 09 Jul 2020   Prob (F-statistic):                        0.00
Time:                        16:22:42   Log-Likelihood:                          491.14
No. Observations:                 400   AIC:                                     -968.3
Df Residuals:                     393   BIC:                                     -940.3
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0029      0.000     -6.805      0.000      -0.004      -0.002
x2             0.0032      0.001      2.647      0.008       0.001       0.006
x3             0.0199      0.005      3.896      0.000       0.010       0.030
x4             0.0006      0.006      0.093      0.926      -0.012       0.013
x5             0.0232      0.006      3.734      0.000       0.011       0.035
x6             0.1309      0.014      9.600      0.000       0.104       0.158
x7             0.0568      0.008      6.953      0.000       0.041       0.073
==============================================================================
Omnibus:                       66.488   Durbin-Watson:                   0.852
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              104.006
Skew:                          -1.026   Prob(JB):                     2.60e-23
Kurtosis:                       4.425   Cond. No.                     1.29e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [96]:
#Now OLS stands for ‘Ordinary Least Squares’, which essentially trains a Linear model. 
#we observe that the higest P-value is for feature 4, which is way over our significance level of 0.05. 
#Hence, we remove it.
x_opt = z[:,[0,1,2,4,5,6]]
x_opt = np.array(x_opt, dtype = float)
regressor_OLS = sm.OLS(endog = w, exog = x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.991
Method:                 Least Squares   F-statistic:                              7057.
Date:                Thu, 09 Jul 2020   Prob (F-statistic):                        0.00
Time:                        16:47:41   Log-Likelihood:                          491.13
No. Observations:                 400   AIC:                                     -970.3
Df Residuals:                     394   BIC:                                     -946.3
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0029      0.000     -6.979      0.000      -0.004      -0.002
x2             0.0032      0.001      2.683      0.008       0.001       0.006
x3             0.0201      0.005      4.182      0.000       0.011       0.030
x4             0.0234      0.006      4.125      0.000       0.012       0.035
x5             0.1311      0.013      9.736      0.000       0.105       0.158
x6             0.0569      0.008      7.021      0.000       0.041       0.073
==============================================================================
Omnibus:                       66.260   Durbin-Watson:                   0.854
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              103.425
Skew:                          -1.024   Prob(JB):                     3.48e-23
Kurtosis:                       4.418   Cond. No.                     1.28e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.28e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [109]:
#dropunnnecessarycolumns
x_opt=newindepv.drop(columns=["sop"])

In [110]:
x_opt

grescore toeflscore universityrating  lor  cgpa research
0        337        118                4  4.5  9.65        1
1        324        107                4  4.5  8.87        1
2        316        104                3  3.5     8        1
3        322        110                3  2.5  8.67        1
4        314        103                2    3  8.21        0
..       ...        ...              ...  ...   ...      ...
395      324        110                3  3.5  9.04        1
396      325        107                3  3.5  9.11        1
397      330        116                4  4.5  9.45        1
398      312        103                3    4  8.78        0
399      333        117                4    4  9.66        1

[400 rows x 6 columns]

In [111]:
#Splitting the Dataset into Training Set and Test Set
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
x_opt_train , x_opt_test , b_train , b_test  = train_test_split(x_opt,newdepv,test_size = 0.2, random_state = 1)

In [112]:
#Fitting multiple linear regression model to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_opt_train,b_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [114]:
#Predicting the test set result
b_pred = regressor.predict(x_opt_test)

In [115]:
b_pred

array([[0.72271437],
       [0.68689973],
       [0.78946812],
       [0.7781855 ],
       [0.8507392 ],
       [0.64428746],
       [0.64148167],
       [0.55153805],
       [0.49347405],
       [0.93566883],
       [0.81431364],
       [0.93594286],
       [0.88305471],
       [0.64978492],
       [0.72979518],
       [0.68919603],
       [0.81848959],
       [0.86938418],
       [0.5121101 ],
       [0.69040733],
       [0.65768419],
       [0.78110402],
       [0.83654545],
       [0.91892213],
       [0.65975593],
       [0.5742423 ],
       [0.72348927],
       [0.71137737],
       [0.90488099],
       [0.65546874],
       [0.9512262 ],
       [0.63497351],
       [0.79388291],
       [0.78573759],
       [0.71429068],
       [0.64798128],
       [0.43978522],
       [0.65832354],
       [0.90794832],
       [0.76625284],
       [0.84334775],
       [0.67927268],
       [0.88040352],
       [0.64943836],
       [0.97716183],
       [0.71669228],
       [0.73703345],
       [0.827

In [117]:
#Checking the score 
print('Train Score: ', regressor.score(x_opt_train, b_train))  
print('Test Score: ', regressor.score(x_opt_test, b_test)) 

Train Score:  0.8003547465729541
Test Score:  0.8095513654709627


In [118]:

# example of a standardization
from numpy import asarray
from sklearn.preprocessing import StandardScaler

# define standard scaler
scaler = StandardScaler()
# transform data
scaled = scaler.fit_transform(x_opt)
print(scaled)

[[ 1.76210664  1.74697064  0.79882862  1.16732114  1.76481828  0.90911166]
 [ 0.62765641 -0.06763531  0.79882862  1.16732114  0.45515126  0.90911166]
 [-0.07046681 -0.56252785 -0.07660001  0.05293342 -1.00563118  0.90911166]
 ...
 [ 1.15124883  1.41704229  0.79882862  1.16732114  1.42900622  0.90911166]
 [-0.41952842 -0.72749202 -0.07660001  0.61012728  0.30403584 -1.09997489]
 [ 1.41304503  1.58200646  0.79882862  0.61012728  1.78160888  0.90911166]]


In [119]:
#Splitting the Dataset into Training Set and Test Set
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
scaled_train , scaled_test , b_train , b_test  = train_test_split(scaled,newdepv,test_size = 0.2, random_state = 1)

Train Score:  0.8003547465729541
Test Score:  0.8095513654709627


In [125]:
x_opt = scaled

In [126]:
x_opt

array([[ 1.76210664,  1.74697064,  0.79882862,  1.16732114,  1.76481828,
         0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862,  1.16732114,  0.45515126,
         0.90911166],
       [-0.07046681, -0.56252785, -0.07660001,  0.05293342, -1.00563118,
         0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862,  1.16732114,  1.42900622,
         0.90911166],
       [-0.41952842, -0.72749202, -0.07660001,  0.61012728,  0.30403584,
        -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862,  0.61012728,  1.78160888,
         0.90911166]])

In [127]:
#Splitting the Dataset into Training Set and Test Set
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
x_opt_train , x_opt_test , b_train , b_test  = train_test_split(x_opt,newdepv,test_size = 0.2, random_state = 1)

In [128]:
#Fitting multiple linear regression model to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_opt_train,b_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [129]:
#Predicting the test set result
b_pred = regressor.predict(x_opt_test)

In [130]:
b_pred

array([[0.72271437],
       [0.68689973],
       [0.78946812],
       [0.7781855 ],
       [0.8507392 ],
       [0.64428746],
       [0.64148167],
       [0.55153805],
       [0.49347405],
       [0.93566883],
       [0.81431364],
       [0.93594286],
       [0.88305471],
       [0.64978492],
       [0.72979518],
       [0.68919603],
       [0.81848959],
       [0.86938418],
       [0.5121101 ],
       [0.69040733],
       [0.65768419],
       [0.78110402],
       [0.83654545],
       [0.91892213],
       [0.65975593],
       [0.5742423 ],
       [0.72348927],
       [0.71137737],
       [0.90488099],
       [0.65546874],
       [0.9512262 ],
       [0.63497351],
       [0.79388291],
       [0.78573759],
       [0.71429068],
       [0.64798128],
       [0.43978522],
       [0.65832354],
       [0.90794832],
       [0.76625284],
       [0.84334775],
       [0.67927268],
       [0.88040352],
       [0.64943836],
       [0.97716183],
       [0.71669228],
       [0.73703345],
       [0.827

In [131]:
#Checking the score 
print('Train Score: ', regressor.score(x_opt_train, b_train))  
print('Test Score: ', regressor.score(x_opt_test, b_test)) 

Train Score:  0.8003547465729541
Test Score:  0.809551365470963


In [132]:

from sklearn.metrics import mean_squared_error


print(mean_squared_error(b_test,b_pred))

0.0044045888920306465
